---
apiVersion: v1
kind: Service
metadata:
  name: keychain
  labels:
    app: keychain
spec:
  selector:
    app: keychain
  ports:
  - name: service-port
    port: 8090
    targetPort: 8090
  - name: monitor-port
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keychain-config
data:
  keychain.properties: |
    spring.datasource.url=jdbc:mysql://${MYSQL_DB_HOST}:3306/keychaindb?serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.username=${MYSQL_DB_USER}
    spring.datasource.password=${MYSQL_DB_PASS}

    # token authorization
    jwt.secret=${JWT_SECRET}
    

    #
    # Below are optional values for phase II
    #
    server.port = 8090

    # redis caching config
    privacyone.keychain.cache.enabled=false
    privacyone.keychain.cache.cluster.enabled=false

    spring.redis.cluster.nodes=127.0.0.1:6379
    spring.redis.host=127.0.0.1
    spring.redis.port=6379

    # rate limit config. rate lime is capacity/time per second
    privacyone.keychain.ratelimit.system.capacity=1000
    privacyone.keychain.ratelimit.system.time=10
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: keychain
  labels:
    app.kubernetes.io/name: keychain
    app: keychain
spec:
  selector:
    matchLabels:
      app: keychain
  replicas: 1
  serviceName: {{ .Release.Name }}-keychain-svc
  template:
    metadata:
      labels:
        app: keychain
    spec:
      containers:
        - name: keychain
          image: {{ .Values.image.keychain }}
          env:
            - name: MYSQL_DB_HOST
              value: {{ .Release.Name }}-mysql-svc
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-user
            - name: MYSQL_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-password
            - name: JWT_SECRET
              value: {{ .Values.jwt.secret }}
              
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
            - containerPort: 5000

          volumeMounts:
            - name: keychain-config-volume
              mountPath: /etc/privacyone/keychain
      volumes:
        - name: keychain-config-volume
          configMap:
            name: keychain-config
