---
apiVersion: v1
kind: Service
metadata:
  name: dpia
  labels:
    app: dpia
spec:
  ports:
  - port: 8097
  selector:
    app: dpia
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dpia-config
data:
  dpia.properties: |
    server.port = 8097

    spring.datasource.url=jdbc:mysql://${MYSQL_DB_HOST}:3306/dpiadb
    spring.datasource.username=${MYSQL_DB_USER}
    spring.datasource.password=${MYSQL_DB_PASS}

    # token authorization
    jwt.secret=${JWT_SECRET}

---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: dpia
  labels:
    app.kubernetes.io/name: dpia
    app: dpia
spec:
  selector:
    matchLabels:
      app: dpia
  replicas: 1
  serviceName: {{ .Release.Name }}-dpia-svc
  template:
    metadata:
      labels:
        app: dpia
    spec:
      containers:
        - name: dpia
          image: {{ .Values.image.dpia }}
          imagePullPolicy: Always
          env:
            - name: MYSQL_DB_HOST
              value: {{ .Release.Name }}-mysql-svc
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-user
            - name: MYSQL_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-password
            - name: JWT_SECRET
              value: {{ .Values.jwt.secret }}
          ports: 
            - containerPort: 8097
          volumeMounts:
            - name: dpia-config-volume
              mountPath: /etc/privacyone/dpia
      volumes:
        - name: dpia-config-volume
          configMap:
            name: dpia-config
