---
apiVersion: v1
kind: Service
metadata:
  name: keychain-analytics
  labels:
    app: keychain-analytics
spec:
  selector:
    app: keychain-analytics
  ports:
    - port: 8095
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keychainanalytics-iam-config
data:
  iam-service-account-key.json: |
    {
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keychainanalytics-config
data:
  keychainanalytics.properties: |
    spring.datasource.url=jdbc:mysql://${MYSQL_DB_HOST}:3306/keychainanalyticsdb?serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.username=${MYSQL_DB_USER}
    spring.datasource.password=${MYSQL_DB_PASS}

    # export job data source
    # dbeam also uses the user name and password
    privacyone.keychain.datasource.url=jdbc:mysql://${MYSQL_DB_HOST}:3306/keychaindb?serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    privacyone.keychain.datasource.username=${MYSQL_DB_USER}
    privacyone.keychain.datasource.password=${MYSQL_DB_PASS}

    # token authorization
    jwt.secret=${JWT_SECRET}

    #
    # Below are optional values for phase II
    #
    server.port = 8095

    # analytics data request ceiling is set to 7 days by default
    privacyone.keychainanalytics.adr.requestTimeThresholdInHour=168

    # schedulers by default every hour
    # keychain database export job
    privacyone.keychainanalytics.cron.export=0 0 * * * *
    # IAM expiration checks
    privacyone.keychainanalytics.cron.iam-expiration-checker=0 0 * * * *

    # data service
    iam.service-account-key.path = /etc/privacyone/keychainanalytics/iam-service-account-key.json
---

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: keychain-analytics
  labels:
    app.kubernetes.io/name: keychain-analytics
    app: keychain-analytics
spec:
  selector:
    matchLabels:
      app: keychain-analytics
  replicas: 1
  serviceName: {{ .Release.Name }}-keychain-analytics-svc
  template:
    metadata:
      labels:
        app: keychain-analytics
    spec:
      containers:
        - name: keychain-analytics
          image: {{ .Values.image.keychainanalytics }}
          env:
            - name: MYSQL_DB_HOST
              value: {{ .Release.Name }}-mysql-svc
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-user
            - name: MYSQL_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-password
            - name: JWT_SECRET
              value: {{ .Values.jwt.secret }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8095
          volumeMounts:
            - name: keychainanalytics-config-volume
              mountPath: /etc/privacyone/keychainanalytics/keychainanalytics.properties
              subPath: keychainanalytics.properties
            - name: keychainanalytics-iam-config-volume
              mountPath: /etc/privacyone/keychainanalytics/iam-service-account-key.json
              subPath: iam-service-account-key.json
      volumes:
        - name: keychainanalytics-config-volume
          configMap:
            name: keychainanalytics-config
        - name: keychainanalytics-iam-config-volume
          configMap:
            name: keychainanalytics-iam-config
