---
apiVersion: v1
kind: Secret
metadata:
  name: license-secret
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: harpocrates-license
type: Opaque
data:
  license-data: "{{ .Values.p1.license }}"
